language: node_js
node_js:
- lts/*
install: |-
  npm ci
  npm install -g codecov
script: |-
  npm run build || travis_terminate 1
  ./node_modules/.bin/nyc report --reporter=lcov
  codecov
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  echo $'**Change log:**<br/>'${log//$'\n'/<br/>}
branches:
  only:
    - master
before_deploy: |-
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  export TAG=$'v'$TRAVIS_COMMIT_MESSAGE
  export BODY=$'**Change log:**<br/>'${log//$'\n'/<br/>}
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: pyMbEx/cRyN1+bJKfY9YHSwGPqfzT6+RMipHV/EeaUH/k3wMAJo3kbAsT/2MzH0N7r7U7miE+9aYPhHT54zRsoczCp1ofZHVr2Wi5n6OoAE2PEy1klnKqignMBmMiOipSflghaLLmy3E6oMBuAKu68FFk5W7GYC+iZORY6PpjM4lyMpBTXhSrvSaGcveJwpXi6fEAUfhFREnwodzHxGvNUOjBZCuO/c1VKYlnGnWH6aQQGTDJt+XQLvsAuuZWcpWb4fLd34fxwG4th+l4+9zqxXoBVSCxoSnE+TE8d0lLC+WY253V0dfFZIHf7Q33bxf8RRX0knLckO9q5LAQTWWL/r093SdhWs4c7MdFypi4u72ZAdmw1FdI8zWno4aqahZ4LOYFINZghbzj1LyzmazMpTwkklLc/bjvINBFURHI1jmZxM7VUEBvfE9jYP8+0tdn8YLyC3z95zu+5gvyUUo/PCuXjCrOec8xWr4ktPuXm90I83Cl1V04msCjaPtlEPYpqaDwTfoslS7jzHDRLhn9oO1NixGiNGqcLoMAwLNp32cLheYl89r6aCixgx/+m1OYzvxu70AAcFnkrOowz3zZCf7bM2jjdyDs4W9+O1lQ/ye58tO2uuAhMJGKGoIxFvzdP/SloqmLr3pOgZGHpcOHHsnjBECNPMSNoONpgy7638=
    file: README.md
    name: Release $TRAVIS_COMMIT_MESSAGE
    tag_name: $TAG
    body: $BODY
    on:
      repo: Guseyn/cutie-rest
      branch:
        - master
      condition: $TRAVIS_COMMIT_MESSAGE =~ ^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$
  - provider: npm
    email: guseynism@gmail.com
    api_key:
      secure: vgy76RatrD+kTRbGsUpq49HQdUXOhFrDeOeVSG0+Js0mnPDCKI5os7RUu1NG5uSMhYuEu0kZT/aCWyKDZ/S4MxF37UAVhwe/KjHgX0ctJgLXQlAf2yXnJ0ymNbT4yrFXE2nENsNrj7859Cqj+N8NQTvtdr3M6YeMEc6aK+JU9OdDJcEHjfBmHP00qUHGuaafy1zDFbvhvUZqVNo46C4gkRFScjGZFIABghQhDuxuZg6pwkN+jtOCFkFBy4I8VD0MiP5qnM1wIv4VMKqqdbLH0arX70WfFIlcUb4te/Rzj3bfPkngJ6PIkjfDLGEEbo0AJBNPtuJyS2pmYc9v2u960YMc3JHCnkhJ2mTMtv3wBHqdmpZ3fYR8Todijy0OqaN+Cv6Ktrc3hA+RjTObgMy96YIIPedDEYCNLsFxrbemPLgGDffgtEM0VEcnXdo35oPiXOMe8Cihk0gWqmC61AKQFZGWwKM/dl7Yy+FPxezFTehiIsO2lZFrO42GOmmRjqqF4WPuYK6xAqlRjWAmfkd4nrRd3xLkxqLEBmg08EdTKRjz5j7Rx2YhaUFB/pbCC85cDxiygAcQFewx+qVqkbP3SluCq5m5o9zpWIKPFOAEKqhJzpJgqQbuvaD+X46W6mb6xQmRLRWFBfyIcGrCdlN/MB/zwZYNavGy5KojbXYBXuQ=
    on:
      repo: Guseyn/cutie-rest
      branch:
        - master
      condition: $TRAVIS_COMMIT_MESSAGE =~ ^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$
